#!/usr/bin/env python3
"""Refresh the `integration-version` dropdown in the bug-report issue form.

GitHub issue forms can't pull dropdown options from releases dynamically, so
this script regenerates the option list from `gh release list` and rewrites
the block between the AUTOGENERATED sentinels in `bug_report.yml`. Run by
`.github/workflows/update-version-dropdown.yml` on every published release.

Only the lines between the sentinels are touched — the surrounding form
(including the permanent "Other / not listed" escape hatch that lives after
the END sentinel) is left byte-for-byte intact.
"""

from __future__ import annotations

import pathlib
import subprocess

TEMPLATE = pathlib.Path(".github/ISSUE_TEMPLATE/bug_report.yml")
BEGIN = "# BEGIN AUTOGENERATED VERSIONS"
END = "# END AUTOGENERATED VERSIONS"
LIMIT = 15


def recent_versions() -> list[str]:
    """Return the most recent release versions, newest first, `v` stripped."""
    result = subprocess.run(
        [
            "gh",
            "release",
            "list",
            "--limit",
            str(LIMIT),
            "--json",
            "tagName",
            "--jq",
            ".[].tagName",
        ],  # noqa: E501
        capture_output=True,
        text=True,
        check=True,
    )
    tags = result.stdout.split()
    return [t[1:] if t.startswith("v") else t for t in tags]


def main() -> None:
    versions = recent_versions()
    if not versions:
        print("No releases found; leaving the template unchanged.")
        return

    text = TEMPLATE.read_text(encoding="utf-8")
    lines = text.splitlines()

    try:
        begin = next(i for i, line in enumerate(lines) if BEGIN in line)
        end = next(i for i, line in enumerate(lines) if END in line)
    except StopIteration as exc:
        raise SystemExit(
            f"Sentinels not found in {TEMPLATE}; expected '{BEGIN}' and '{END}'."
        ) from exc

    # The option items share the indentation of the sentinel comment line.
    indent = lines[begin][: lines[begin].index("#")]
    rebuilt = lines[: begin + 1] + [f"{indent}- {version}" for version in versions] + lines[end:]
    new_text = "\n".join(rebuilt) + ("\n" if text.endswith("\n") else "")

    if new_text == text:
        print("Version dropdown already up to date.")
        return

    TEMPLATE.write_text(new_text, encoding="utf-8")
    print(f"Refreshed version dropdown with {len(versions)} releases (newest: {versions[0]}).")


if __name__ == "__main__":
    main()
