"""The rule #515 encodes: our floors must fit inside the core's pins.

The script itself needs the network (it fetches Home Assistant's
``package_constraints.txt`` and asks pip to resolve), so CI runs it as a job.
What is tested here is the part that decides pass or fail — parsing the
constraint file and comparing it against the floors in ``manifest.json`` — with
constraint lines copied verbatim from real releases.
"""

from __future__ import annotations

import importlib.util
from pathlib import Path
from typing import TYPE_CHECKING

import pytest

if TYPE_CHECKING:
    from types import ModuleType

_SCRIPT = Path(__file__).resolve().parents[2] / "scripts" / "check_ha_requirement_floors.py"

# Verbatim excerpts. 2025.10.0 is the last core whose grpcio pin is below our
# floor; 2025.11.0 is the first that satisfies it (#513).
_CONSTRAINTS_2025_10_0 = """
# Automatically generated by gen_requirements_all.py, do not edit
aiohttp==3.13.0
grpcio==1.72.1
grpcio-status==1.72.1
protobuf==6.32.0
pycryptodome>=3.6.6
"""

_CONSTRAINTS_2025_11_0 = """
# Automatically generated by gen_requirements_all.py, do not edit
aiohttp==3.13.2
grpcio==1.75.1
grpcio-status==1.75.1
protobuf==6.32.0
pycryptodome>=3.6.6
"""


@pytest.fixture(scope="module")
def script() -> ModuleType:
    spec = importlib.util.spec_from_file_location("check_ha_requirement_floors", _SCRIPT)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class TestConstraintParsing:
    def test_reads_exact_pins_and_floors(self, script: ModuleType) -> None:
        pins = script._parse_constraints(_CONSTRAINTS_2025_11_0)
        assert pins["grpcio"] == ("==", "1.75.1")
        assert pins["pycryptodome"] == (">=", "3.6.6")

    def test_ignores_comments_and_blank_lines(self, script: ModuleType) -> None:
        pins = script._parse_constraints(_CONSTRAINTS_2025_11_0)
        assert "#" not in "".join(pins)
        assert set(pins) == {"aiohttp", "grpcio", "grpcio-status", "protobuf", "pycryptodome"}


class TestFloorsAgainstPins:
    def test_a_floor_above_the_pin_is_rejected(self, script: ModuleType) -> None:
        failures = script._check_pins(
            ["grpcio>=1.75.1"], script._parse_constraints(_CONSTRAINTS_2025_10_0), "2025.10.0"
        )
        assert len(failures) == 1
        assert "grpcio==1.72.1" in failures[0]

    def test_a_floor_the_pin_satisfies_passes(self, script: ModuleType) -> None:
        assert not script._check_pins(
            ["grpcio>=1.75.1"], script._parse_constraints(_CONSTRAINTS_2025_11_0), "2025.11.0"
        )

    def test_a_pin_above_our_floor_passes(self, script: ModuleType) -> None:
        """We carry no upper caps, so a core ahead of our floor is never a problem."""
        assert not script._check_pins(
            ["protobuf>=6.31.1"], script._parse_constraints(_CONSTRAINTS_2025_11_0), "2025.11.0"
        )

    def test_an_unconstrained_requirement_passes(self, script: ModuleType) -> None:
        assert not script._check_pins(
            ["firebase-messaging>=0.4.5"],
            script._parse_constraints(_CONSTRAINTS_2025_11_0),
            "2025.11.0",
        )

    def test_a_core_floor_rather_than_a_pin_passes(self, script: ModuleType) -> None:
        """``pycryptodome>=3.6.6`` is a floor, not a cap — our 3.20 fits above it."""
        assert not script._check_pins(
            ["pycryptodome>=3.20"], script._parse_constraints(_CONSTRAINTS_2025_11_0), "2025.11.0"
        )


class TestRealManifestIsChecked:
    def test_every_manifest_requirement_is_a_floor_the_script_understands(
        self, script: ModuleType
    ) -> None:
        """A requirement the script cannot parse would be silently unguarded."""
        for requirement in script._requirements():
            assert script._REQUIREMENT.fullmatch(requirement.strip()), (
                f"{requirement!r} in manifest.json is not a 'name>=version' floor, so "
                "check_ha_requirement_floors.py cannot compare it against the core's pins"
            )

    def test_the_declared_minimum_is_what_gets_checked(self, script: ModuleType) -> None:
        assert script._declared_minimum() == script._declared_minimum().strip()
        assert script._version(script._declared_minimum()) >= (2025, 11, 0)
